"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var arrays_1 = require("./utilities/arrays");
var numbers_1 = require("./utilities/numbers");
var strings_1 = require("./utilities/strings");
var numArr = [3, 4, 5, 6];
var wordArr = ["cat", "dog", "rabbit", "bird"];
var arrSum = (0, arrays_1.addArr)(numArr);
var mixArr = (0, arrays_1.concatArr)(numArr, wordArr);
var myNum = "15" % 2;
console.log((0, arrays_1.cut3)(mixArr));
console.log((0, numbers_1.sum)(arrSum, myNum));
console.log((0, strings_1.capitalize)("the quick brown fox"));
console.log((0, numbers_1.multiply)("5", 8));
console.log((0, arrays_1.lgNum)(mixArr));
